# infra options
gpus: 1
accelerator: "dp" # use ddp for gpus > 1. Also see PyTorch Lightning documentation on distributed training.
workers: 8 # I recommend tuning this parameter for faster data augmentation processing
dataset_dir: "./data"

# train options
seed: 42
batch_size: 48
max_epochs: 200
dataset: "magnatagatune" # ["magnatagatune", "msd", "gtzan", "librispeech", "audio"]
supervised: 0 # train with supervised baseline

# SimCLR model options
projection_dim: 64 # Projection dim. of SimCLR projector

# loss options
optimizer: "Adam" # or LARS (experimental)
learning_rate: 0.0003
weight_decay: 1.0e-6 # "optimized using LARS [...] and weight decay of 10−6"
temperature: 0.5 # see appendix B.7.: Optimal temperature under different batch sizes

# reload options
checkpoint_path: "" # set to the directory containing `checkpoint_##.tar`
resume_checkpoint_path: ""

# logistic regression options
finetuner_mlp: 0
finetuner_checkpoint_path: ""
finetuner_max_epochs: 200
finetuner_batch_size: 256
finetuner_learning_rate: 0.001 # for SampleCNN
#finetuner_learning_rate: 0.005 # for Inception

# audio data augmentation options
audio_length: 59049
sample_rate: 22050
transforms_polarity: 0.8
transforms_noise: 0.01
transforms_gain: 0.3
transforms_filters: 0.8
transforms_delay: 0.3
transforms_pitch: 0.6
transforms_reverb: 0.6

# other options
alpha: 1.0
loss2_weight: 1.0
loss1_ratio: 22.00
eval_only: 0
train_only: 0
load_only_clmr_part: 1
spec_aug: 0
spec_aug_timemasking: 0.2
spec_aug_timestretch: 0.1
spec_aug_p: 0.0

save_emb_array: 1
save_clip_emb: 0
save_agct: 0
finetune_aug_less: 0
aug_pattern: 0

# for Mind-Music experiment
eeg_type: "raw"
training_date: "tmp"
loss_function: "nt_xent"
eeg_normalization: "none"
openmiir_augmentation: "no_augmentation"
rmNoisySubject: 0
audio_sample_rate: 44100
eeg_sample_rate: 125
eeg_length: 375
audio_clip_length: 3.0
dim_reduction: 1
clamp_value: 20
split_seed: 42
class_song_id: "[21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]" # All NMED-H song IDs 
train_test_splitting: "none"
detach_z_c: 0
## for gaussian noise
max_amplitude: 0.015
min_amplitude: 0.001
weight_r: 1.0
weight_c: 1.0
weight_clip: 1.0

## for sliding window
window_size: 1000
stride: 250

## for shifting time delay
shifting_time: 0